#!/bin/bash

#BSUB -J fpPoP33
#BSUB -o output/test-%J.out
#BSUB -e output/test-%J.err
#BSUB -q normal
#BSUB -n 6
#BSUB -R rusage[mem=8192]

# Some important variables to check (Can be removed later)
echo '---PROCESS RESOURCE LIMITS---'
ulimit -a
echo '---SHARED LIBRARY PATH---'
echo $LD_LIBRARY_PATH
echo '---APPLICATION SEARCH PATH:---'
echo $PATH
echo '---LSF Parameters:---'
printenv | grep '^LSF'
echo '---LSB Parameters:---'
printenv | grep '^LSB'
echo '---LOADED MODULES:---'
module list
echo '---SHELL:---'
echo $SHELL
echo '---HOSTNAME:---'
hostname
echo '---GROUP MEMBERSHIP (files are created in the first group listed):---'
groups
echo '---DEFAULT FILE PERMISSIONS (UMASK):---'
umask
echo '---CURRENT WORKING DIRECTORY:---'
pwd
echo '---DISK SPACE QUOTA---'
df .
echo '---TEMPORARY SCRATCH FOLDER ($TMPDIR):---'
echo $TMPDIR

# Add your job command here

#module load Miniconda3/4.4.10 #Anaconda3/5.2.0
module load miniconda3/latest
conda activate BioInfoEnv
conda info --envs

file=$(cat ./SRR_Acc_List_PAIRED.txt)
in_file="/data/guilherme/posttransplant_PRJNA542833_GSE131179/paired_end/raw_reads/"
out_file="/data/guilherme/posttransplant_PRJNA542833_GSE131179/paired_end/trimmed_reads/"

for line in $file
do
    fastp --dedup -i ${in_file}${line}_1.fastq -I ${in_file}${line}_2.fastq -o ${out_file}${line}_1.trimmed.fastq -O ${out_file}${line}_2.trimmed.fastq
done
