#!/bin/bash

#BSUB -J sraPos2P
#BSUB -o output/test-%J.out
#BSUB -e output/test-%J.err
#BSUB -q normal
#BSUB -n 6
#BSUB -R rusage[mem=512]

# Some important variables to check (Can be removed later)
echo '---PROCESS RESOURCE LIMITS---'
ulimit -a
echo '---SHARED LIBRARY PATH---'
echo $LD_LIBRARY_PATH
echo '---APPLICATION SEARCH PATH:---'
echo $PATH
echo '---LSF Parameters:---'
printenv | grep '^LSF'
echo '---LSB Parameters:---'
printenv | grep '^LSB'
echo '---LOADED MODULES:---'
module list
echo '---SHELL:---'
echo $SHELL
echo '---HOSTNAME:---'
hostname
echo '---GROUP MEMBERSHIP (files are created in the first group listed):---'
groups
echo '---DEFAULT FILE PERMISSIONS (UMASK):---'
umask
echo '---CURRENT WORKING DIRECTORY:---'
pwd
echo '---DISK SPACE QUOTA---'
df .
echo '---TEMPORARY SCRATCH FOLDER ($TMPDIR):---'
echo $TMPDIR

# Add your job command here

#module load miniconda3/4.12.0
#conda activate BioInfoEnv
#echo conda info --envs
module load sratoolkit/3.0.0

file=$(cat ./SRR_Acc_List_PAIRED.txt)
for line in $file
do
    fasterq-dump --split-files -A $line -O /data/guilherme/posttransplant_PRJNA542833_GSE131179/paired_end/raw_reads/
done
